In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/logistic

/content/drive/MyDrive/logistic


In [ ]:
!pwd

/content/drive/MyDrive/logistic


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpl

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/logistic/emnist-letters-train.csv', header= None)
train = df_train.to_numpy()
df_test = pd.read_csv('/content/drive/MyDrive/logistic/emnist-letters-test.csv', header= None)
test = df_test.to_numpy()

In [ ]:
input1 = train[0:60000, 1:]/255 #Scaling values between 0 and 1
ylabels = train[0:60000, 0]

In [ ]:
x0 = np.ones([np.shape(input1)[0], 1])
input = np.concatenate((x0, input1),axis = 1).T
print(np.shape(input))

(60000, 785)


In [ ]:
uniquech = set(ylabels)
logisticY = np.zeros([np.size(ylabels), len(uniquech)])
for i in range(np.size(ylabels)):
  for j in range(1, len(uniquech)+1):
    if ylabels[i] == j:
      logisticY[i,j-1] = 1
logisticY = logisticY.T
print(logisticY)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
def sigmoid(z):
  return 1/ (1+np.exp(-z))

In [ ]:
# def train(x, y, alpha, iterations):
#   #initialise thetas
#   w1 = np.random.random([x.shape[1], 100])
#   w2 = np.random.random([100, 50])
#   w3 = np.random.random([50, len(uniquech)])


#   for iter in range(iterations):

#   #forward
#     a2 = sigmoid(np.dot(x, w1))
#     a3 = sigmoid(np.dot(a2, w2))
#     out = sigmoid(np.dot(a3, w3))
# #errors
#     d4 = out - y
#     d3 = (np.dot(d4 ,w3.T))*(a3*(1 - a3))
#     d2 = (np.dot(d3, w2.T ))*(a2*(1-a2))
# #backward
#     pd_w3 = np.dot(a3.T, d4)
#     pd_w2 = np.dot(a2.T, d3)
#     pd_w1 = np.dot(x.T , d2)

#     w1 = w1 - ((alpha*pd_w1) / (x.shape[0]))
#     w2 = w2 - ((alpha*pd_w2) / (x.shape[0]))
#     w3 = w3 - ((alpha*pd_w3) / (x.shape[0]))
#   return w1

In [ ]:
def train(x, y, alpha, iterations):

#initialise thetas
  w1 = np.random.random([x.shape[1], 50])*0.01
  w2 = np.random.random([50, len(uniquech)])*0.01
  b1 = np.ones([1, 50], dtype = int)
  b2 = np.ones([1, len(uniquech)], dtype = int)
  for iter in range(iterations):

#forward
    z2 = np.dot(x, w1) + b1
    a2 = sigmoid(z2)
    z3 = np.dot(a2, w2) + b2
    out = sigmoid(z3)
    
#errors
    d3 = out - y
    d2 = (np.dot(d3 ,w2.T)) * (a2*(1 - a2))

#backward
    pd_w2 = np.dot(a2.T, d3) / (x.shape[0])
    pd_w1 = np.dot(x.T , d2) / (x.shape[0])
    pd_b2 = np.sum(d3) / (x.shape[0])
    pd_b1 = np.sum(d2) / (x.shape[0])
    w1 = w1 - (alpha*pd_w1) 
    w2 = w2 - (alpha*pd_w2) 
    b1 = b1 - (alpha*pd_b1)
    b2 = b2 - (alpha*pd_b2)


  return w1, w2, out

In [13]:
w1, w2, out = train(x=input, y=logisticY, alpha = 0.01, iterations=200)

In [ ]:
pd.DataFrame(out)

0         1         2         3         4         5         6   \
0      0.033592  0.033924  0.033576  0.033875  0.034469  0.032954  0.033673   
1      0.033306  0.033639  0.033290  0.033588  0.034179  0.032672  0.033387   
2      0.039956  0.040323  0.039937  0.040267  0.040920  0.039256  0.040042   
3      0.035720  0.036064  0.035704  0.036010  0.036627  0.035059  0.035803   
4      0.036457  0.036805  0.036440  0.036752  0.037378  0.035790  0.036538   
...         ...       ...       ...       ...       ...       ...       ...   
59995  0.038629  0.038994  0.038614  0.038938  0.039581  0.037944  0.038718   
59996  0.038616  0.038971  0.038597  0.038918  0.039561  0.037925  0.038701   
59997  0.042878  0.043263  0.042862  0.043206  0.043882  0.042150  0.042972   
59998  0.042415  0.042790  0.042398  0.042734  0.043408  0.041694  0.042508   
59999  0.038934  0.039300  0.038922  0.039247  0.039889  0.038250  0.039024   

             7         8         9   ...        16        17        18  \
0      0.033610  0.032093  0.033200  ...  0.034121  0.033748  0.033781   
1      0.033324  0.031814  0.032916  ...  0.033831  0.033461  0.033492   
2      0.039974  0.038304  0.039523  ...  0.040536  0.040131  0.040159   
3      0.035737  0.034167  0.035314  ...  0.036266  0.035880  0.035914   
4      0.036476  0.034886  0.036046  ...  0.037013  0.036620  0.036652   
...         ...       ...       ...  ...       ...       ...       ...   
59995  0.038649  0.037009  0.038210  ...  0.039200  0.038801  0.038832   
59996  0.038632  0.036993  0.038190  ...  0.039184  0.038781  0.038818   
59997  0.042895  0.041169  0.042429  ...  0.043482  0.043060  0.043091   
59998  0.042435  0.040711  0.041969  ...  0.043013  0.042592  0.042631   
59999  0.038954  0.037310  0.038513  ...  0.039510  0.039109  0.039138   

             19        20        21        22        23        24        25  
0      0.033086  0.034383  0.034271  0.034073  0.033879  0.032793  0.033750  
1      0.032802  0.034092  0.033982  0.033786  0.033590  0.032511  0.033462  
2      0.039398  0.040823  0.040701  0.040482  0.040266  0.039075  0.040127  
3      0.035196  0.036537  0.036424  0.036216  0.036011  0.034895  0.035880  
4      0.035928  0.037284  0.037169  0.036960  0.036756  0.035620  0.036623  
...         ...       ...       ...       ...       ...       ...       ...  
59995  0.038085  0.039481  0.039364  0.039149  0.038938  0.037768  0.038797  
59996  0.038068  0.039466  0.039345  0.039135  0.038922  0.037750  0.038784  
59997  0.042302  0.043778  0.043652  0.043424  0.043204  0.041967  0.043057  
59998  0.041844  0.043309  0.043183  0.042960  0.042739  0.041508  0.042594  
59999  0.038385  0.039790  0.039672  0.039458  0.039244  0.038069  0.039108  

[60000 rows x 26 columns]

In [14]:
index = np.argmax(out, axis=1)
pred = np.zeros(out.shape)
for i in range(np.shape(out)[0]):
  pred[i][index[i]] = 1

In [15]:
prediction = np.zeros([np.size(ylabels) , 1], dtype = int)
for i in range(np.shape(out)[0]):
  for j in range(np.shape(out)[1]):
    if pred[i][j] == 1:
      prediction[i][0] = j + 1

In [ ]:
accuracy(np.vstack(ylabels) , prediction)

Accuracy is 3.8833333333333337 %


3.8833333333333337

In [17]:
testX1 = test[:, 1:]/255
testY = test[:, 0]

In [ ]:
x0t = np.ones([np.shape(testX1)[0], 1])
testX = np.concatenate((x0t, testX1),axis = 1)

In [18]:
a2 = sigmoid(np.dot(testX, w1))
outtest = sigmoid(np.dot(a2, w2))

In [ ]:
pd.DataFrame(outtest)

0         1         2         3         4         5         6   \
0      0.130142  0.130981  0.130106  0.130873  0.132393  0.128456  0.130338   
1      0.119683  0.120529  0.119635  0.120408  0.121903  0.118068  0.119879   
2      0.138092  0.138951  0.138056  0.138814  0.140369  0.136400  0.138299   
3      0.112973  0.113793  0.112917  0.113657  0.115134  0.111374  0.113160   
4      0.135533  0.136399  0.135465  0.136250  0.137811  0.133842  0.135729   
...         ...       ...       ...       ...       ...       ...       ...   
14795  0.138722  0.139552  0.138662  0.139400  0.140992  0.137009  0.138906   
14796  0.144638  0.145507  0.144581  0.145356  0.146919  0.142929  0.144837   
14797  0.115263  0.116076  0.115217  0.115937  0.117429  0.113639  0.115451   
14798  0.131340  0.132224  0.131288  0.132057  0.133615  0.129672  0.131538   
14799  0.132693  0.133564  0.132644  0.133430  0.134954  0.131016  0.132899   

             7         8         9   ...        16        17        18  \
0      0.130158  0.126217  0.129102  ...  0.131505  0.130531  0.130598   
1      0.119713  0.115859  0.118676  ...  0.120998  0.120096  0.120139   
2      0.138115  0.134120  0.137050  ...  0.139486  0.138486  0.138579   
3      0.113004  0.109211  0.111989  ...  0.114281  0.113362  0.113420   
4      0.135539  0.131549  0.134489  ...  0.136903  0.135932  0.135998   
...         ...       ...       ...  ...       ...       ...       ...   
14795  0.138723  0.134703  0.137660  ...  0.140087  0.139096  0.139188   
14796  0.144641  0.140613  0.143566  ...  0.146006  0.145025  0.145097   
14797  0.115271  0.111466  0.114254  ...  0.116571  0.115638  0.115711   
14798  0.131354  0.127400  0.130312  ...  0.132696  0.131751  0.131803   
14799  0.132723  0.128747  0.131667  ...  0.134045  0.133101  0.133170   

             19        20        21        22        23        24        25  
0      0.128794  0.132143  0.131874  0.131377  0.130872  0.128027  0.130556  
1      0.118386  0.121660  0.121409  0.120912  0.120412  0.117648  0.120091  
2      0.136732  0.140152  0.139853  0.139334  0.138827  0.135976  0.138499  
3      0.111694  0.114921  0.114651  0.114139  0.113682  0.110964  0.113366  
4      0.134188  0.137570  0.137262  0.136783  0.136256  0.133399  0.135932  
...         ...       ...       ...       ...       ...       ...       ...  
14795  0.137367  0.140763  0.140453  0.139959  0.139429  0.136587  0.139104  
14796  0.143274  0.146677  0.146412  0.145884  0.145363  0.142474  0.145027  
14797  0.113971  0.117199  0.116924  0.116447  0.115957  0.113239  0.115636  
14798  0.130017  0.133363  0.133073  0.132578  0.132070  0.129257  0.131745  
14799  0.131363  0.134721  0.134444  0.133930  0.133438  0.130592  0.133109  

[14800 rows x 26 columns]

In [19]:
indext = np.argmax(outtest, axis=1)
predt = np.zeros(outtest.shape)
for i in range(np.shape(outtest)[0]):
  predt[i][indext[i]] = 1

In [20]:
predictiont = np.zeros([np.size(testY) , 1], dtype = int)
for i in range(np.shape(outtest)[0]):
  for j in range(np.shape(outtest)[1]):
    if predt[i][j] == 1:
      predictiont[i][0] = j + 1

In [ ]:
np.unique(predictiont)

array([15])

In [ ]:
def accuracy(label, preds):
  truthtable = (label == preds).astype(int)
  truthlist = truthtable.tolist()
  accuracy = (truthlist.count([1]))*(100/(np.shape(preds)[0]))
  print("Accuracy is", accuracy , "%" )
  return accuracy

In [ ]:
accuracy(np.vstack(testY) , predictiont)

Accuracy is 5.405405405405405 %


5.405405405405405