In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%cd /content/drive/MyDrive/logistic

/content/drive/MyDrive/logistic


In [ ]:
!pwd

/content/drive/MyDrive/logistic


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mpl

In [ ]:
df_train = pd.read_csv('/content/drive/MyDrive/logistic/emnist-letters-train.csv', header= None)
train = df_train.to_numpy()

In [ ]:
input1 = train[0:62000, 1:]/255 #Scaling values between 0 and 1
ylabels = train[0:62000, 0]

In [ ]:
x0 = np.ones([np.shape(input1)[0], 1])
input = np.concatenate((x0, input1),axis = 1)
print(np.shape(input))

(62000, 785)


In [ ]:
uniquech = set(ylabels)
logisticY = np.zeros([np.size(ylabels), len(uniquech)])
for i in range(np.size(ylabels)):
  for j in range(1, len(uniquech)+1):
    if ylabels[i] == j:
      logisticY[i,j-1] = 1
print(logisticY)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
def sigmoid(z):
  return 1/ (1+np.exp(-z))

In [ ]:
def accuracy(label, preds):
  truthtable = (label == preds).astype(int)
  truthlist = truthtable.tolist()
  accuracy = (truthlist.count([1]))*(100/(np.shape(preds)[0]))
  print("Accuracy is", accuracy , "%" )
  return accuracy

In [ ]:
def train(x, y, alpha, iterations):

#initialise thetas
  w1 = np.random.random([x.shape[1], 100]) - 0.5
  w2 = np.random.random([100, len(uniquech)]) - 0.5
  b1 = np.zeros([1, 100], dtype = int)
  b2 = np.zeros([1, len(uniquech)], dtype = int)
  for iter in range(iterations):

#forward
    z2 = np.dot(x, w1) + b1
    a2 = sigmoid(z2)
    z3 = np.dot(a2, w2) + b2
    out = sigmoid(z3)
    
#errors
    d3 = (out - y)
    d2 = (np.dot(d3 ,w2.T)) * (a2*(1 - a2))

#backward
    pd_w2 = np.dot(a2.T, d3) / (x.shape[0])
    pd_w1 = np.dot(x.T , d2) / (x.shape[0])
    pd_b2 = np.sum(d3) / (x.shape[0])
    pd_b1 = np.sum(d2) / (x.shape[0])
    w1 = w1 - (alpha*pd_w1) 
    w2 = w2 - (alpha*pd_w2) 
    b1 = b1 - (alpha*pd_b1)
    b2 = b2 - (alpha*pd_b2)

#cost function
    cost = (1/(x.shape[1])) * np.sum((-y*np.log(out)) - ((1-y) *np.log(1 - out)))
    if( iter % (iterations/10) == 0):
      print("Cost after", iter , "is :", cost)
    
  return w1, w2, out

In [ ]:
w1, w2, out = train(x=input, y=logisticY, alpha = 0.3, iterations= 5000)

Cost after 0 is : 2353.077878999959
Cost after 500 is : 161.26178968088868
Cost after 1000 is : 138.15532578165644
Cost after 1500 is : 124.51452118712747
Cost after 2000 is : 114.67497877606499
Cost after 2500 is : 107.02689907425396
Cost after 3000 is : 100.85037988037361
Cost after 3500 is : 95.75284229914207
Cost after 4000 is : 91.47794183619253
Cost after 4500 is : 87.84439681706836


**TEST**

In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/logistic/emnist-letters-test.csv', header= None)
test = df_test.to_numpy()

In [ ]:
testX1 = test[:, 1:]/255
testY = test[:, 0]

In [ ]:
x0t = np.ones([np.shape(testX1)[0], 1])
testX = np.concatenate((x0t, testX1),axis = 1)

In [ ]:
a2 = sigmoid(np.dot(testX, w1))
outtest = sigmoid(np.dot(a2, w2))

In [ ]:
indext = np.argmax(outtest, axis=1)
predt = np.zeros(outtest.shape)
for i in range(np.shape(outtest)[0]):
  predt[i][indext[i]] = 1

In [ ]:
predictiont = np.zeros([np.size(testY) , 1], dtype = int)
for i in range(np.shape(outtest)[0]):
  for j in range(np.shape(outtest)[1]):
    if predt[i][j] == 1:
      predictiont[i][0] = j + 1

In [ ]:
accuracy(np.vstack(testY) , predictiont)

Accuracy is 77.72297297297298 %


77.72297297297298